name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*.*.*' # push to versioned tag will trigger this build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set version
        id: vars
        uses: battila7/get-version-action@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Run Tests
        env:
          TON_NETWORK_ADDRESS: http://localhost:8888
        run: |
          docker run -d --name local-node -p8888:80 tonlabs/local-node
          dotnet restore
          dotnet test
      - name: Pack
        run: dotnet pack -c Release
          --version-suffix ${{ steps.vars.outputs.version }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: Release ${{ steps.vars.outputs.version }}
          draft: false
          prerelease: false
      - name: Deploy Nuget Packages
        run: dotnet nuget push **/*.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --skip-duplicate
          --source https://api.nuget.org/v3/index.json
          --no-symbols true
